object: Use 2024 edition (#291)
The current code won't compile with `cargo 1.90.0-nightly (6833aa715 2025-07-13)`

```
   Compiling lightswitch-object v0.3.1 (/Users/javierhonduco/src/lightswitch/lightswitch-object)
error: let chains are only allowed in Rust 2024 or later
   --> lightswitch-object/src/object.rs:158:30
    |
158 |                 if is_zig && let Some((low_address, high_address)) = zig_first_frame {
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

Upgrading to 2024 edition to make this compile for older and newer versions of rustc.

Test Plan
=========

CI