build/nix: Update nixpkgs
Most notably, this changed rustc from `rustc 1.96.0-nightly (3b1b0ef4d
2026-03-11)` to `rustc 1.99.0-nightly (3659db0d3 2026-07-05)`.

There were some linking errors that required changing the way things are
linked.

```
"-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: /nix/store/xy2zvwkq0rsm0gqlzjbd14vzf8vqv3ic-binutils-2.46/bin/ld.bfd: /home/javierhonduco/git/lightswitch/target/debug/deps/liblibbpf_sys-a49be7c17d4badeb.rlib(crc32.o): in function `crc32':
          (.text+0xaac): multiple definition of `crc32'; /home/javierhonduco/git/lightswitch/target/debug/deps/liblibbpf_sys-a49be7c17d4badeb.rlib(crc32.o):(.text+0x0): first defined here
          collect2: error: ld returned 1 exit status
```

Test Plan
=========

CI

Signed-off-by: Francisco Javier Honduvilla Coto <javierhonduco@gmail.com>