Fix BPF process mapping deletion
Before this commit, the data stored for a process mapping in BPF was
only removed if the reference count of the object file reached zero.
This is obviously wrong and this data should always be removed when a
mapping is unmaped or a process exits.

This in turn causes a pretty nasty bug that won't show if profiling a
set of relatively static processes but will otherwise. This is roughly
what can happen.

1. Processes start being profiled and eventually exit. It doesn't matter if these
   processes are long lived or not, but the higher the rate of exits / munmaps,
   the worse;
2. In the cleanup, only when the reference count of an object reaches
   zero the mappings will be reclaimed, so for all the typical shared
objects (libc, libssl, etc) the mappings will never be deleted for most
processes;
3. Eventually the BPF maps storing process mappings get full and the
   eviction process kicks in. Since this logic also calls the function
with this bug, it won't be able to accomodate space for new mappings and
any attempts to profile new process will keep on failing here;

Test Plan
=========

The modified integration test didn't catch this as the reference count
was zero once a single process had been added and removed, hence the
mappings were removed too.

I've updated the tests to catch this precise bug. With the previous
logic and this test, it fails, as expected:

```
---- profiler::tests::test_bpf_cleanup stdout ----

thread 'profiler::tests::test_bpf_cleanup' (366080) panicked at src/profiler.rs:2215:9:
assertion `left == right` failed
  left: 32
 right: 31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```